Object.defineProperty(exports, "__esModule", {
  value: true
}), exports.default={
  LOCALSTORE_DATA:"LOCALSTORE_DATA",
  SEARCH_HISTORY_CACHE:"SEARCH_HISTORY_CACHE",
  LOCALSTORE_DATA_NEW:"LOCALSTORE_DATA_NEW",
  SEARCH_HISTORY_CACHE_NEW:"SEARCH_HISTORY_CACHE_NEW",
  CAN_SHOW_CARD_COLLECTION_TIP:"CAN_SHOW_CARD_COLLECTION_TIP",
  SHOULDINITALL:"SHOULDINITALL",
  ISTODAYGETHOT:"ISTODAYGETHOT"
}
